"""Define configuration models and load validated application settings."""

import os
import math
from pathlib import Path
from typing import Literal

import yaml
from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError, model_validator

load_dotenv()


class AgentConfig(BaseModel):
    """Configure agent settings."""

    max_loops: int = Field(default=15, gt=0)


class LoggingConfig(BaseModel):
    """Configure logging settings."""

    level: str = "INFO"
    format: str = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


class MemoryConfig(BaseModel):
    """Configure memory settings."""

    redis_url: str = "redis://localhost:6380"
    qdrant_url: str = "http://localhost:6333"
    working_ttl_seconds: int = 1800
    pg_url: str = "postgresql://litagent:litagent@localhost:5433/litagent"


class ContextConfig(BaseModel):
    """Configure context assembly and review token budgets."""

    # This budget excludes tokens generated by the model.
    max_tokens: int = Field(default=32768, ge=8000, le=262144)
    compact_threshold: float = Field(default=0.85, gt=0, le=1.0)
    synthesis_evidence_max_tokens: int = Field(default=16000, ge=1000, le=64000)
    synthesis_papers_max_tokens: int = Field(default=8000, ge=500, le=32000)
    evidence_top_k_per_section: int = Field(default=12, ge=1, le=30)
    evidence_max_items: int = Field(default=60, ge=5, le=150)
    evidence_per_paper_cap: int = Field(default=4, ge=1, le=10)
    review_evidence_max_tokens: int = Field(default=10000, ge=1000, le=64000)
    review_draft_max_tokens: int = Field(default=14000, ge=1000, le=64000)
    review_feedback_max_tokens: int = Field(default=2000, ge=200, le=16000)

    @model_validator(mode="after")
    def _check_synthesis_budget_fits(self):
        if (
            self.synthesis_evidence_max_tokens + self.synthesis_papers_max_tokens
            > self.max_tokens
        ):
            raise ValueError(
                f"synthesis_evidence_max_tokens ({self.synthesis_evidence_max_tokens}) "
                f"+ synthesis_papers_max_tokens ({self.synthesis_papers_max_tokens}) "
                f"exceeds max_tokens ({self.max_tokens})"
            )
        return self

    @model_validator(mode="after")
    def _check_review_budget_fits(self):
        if (
            self.review_evidence_max_tokens
            + self.review_draft_max_tokens
            + self.review_feedback_max_tokens
            > self.max_tokens
        ):
            raise ValueError(
                f"review_evidence_max_tokens ({self.review_evidence_max_tokens}) "
                f"+ review_draft_max_tokens ({self.review_draft_max_tokens}) "
                f"+ review_feedback_max_tokens ({self.review_feedback_max_tokens}) "
                f"exceeds max_tokens ({self.max_tokens})"
            )
        return self


class OrchestratorConfig(BaseModel):
    """Configure orchestrator settings."""

    timeout_ms: int = Field(default=600000, gt=0)
    max_concurrent: int = Field(default=5, gt=0)


class LLMConfig(BaseModel):
    """Configure the LLM provider and generation defaults."""

    base_url: str = "https://api.deepseek.com"
    model: str = "deepseek-v4-flash"
    # This cap applies when a task does not provide a narrower override.
    max_tokens: int = Field(default=20000, gt=0)
    temperature: float = Field(default=0.1, ge=0, le=2.0)


class AdversarialConfig(BaseModel):
    """Configure adversarial settings."""

    max_rounds: int = Field(default=3, gt=0, le=5)
    pass_threshold: float = Field(default=0.8, gt=0, le=1.0)
    review_max_tokens: int = Field(default=12288, gt=0)


class PlannerConfig(BaseModel):
    """Configure planner settings."""

    decompose_enabled: bool = True
    max_sub_queries: int = Field(default=3, ge=1, le=3)
    max_tokens: int = Field(default=8192, gt=0)
    temperature: float = Field(default=0.3, ge=0.0, le=2.0)
    use_procedural_profiles: bool = False
    procedural_min_samples: int = Field(default=3, ge=1)


class MCPServerConfig(BaseModel):
    """Configure one MCP server connection and its sandbox policy."""

    transport: str = "stdio"
    command: str | None = None
    args: list[str] = []
    env: dict | None = None
    url: str | None = None
    headers: dict | None = None
    enabled: bool = True
    sandboxed: bool = False
    sandbox_network: str = "none"


class SafetyConfig(BaseModel):
    """Configure safety settings."""

    max_cost_tokens: int = Field(default=500_000, gt=0)
    cost_warn_ratio: float = Field(default=0.8, gt=0, le=1.0)


class ResilienceConfig(BaseModel):
    """Configure resilience settings."""

    cb_fail_threshold: int = Field(default=5, gt=0)
    cb_cooldown_seconds: int = Field(default=60, gt=0)


class ExtractorConfig(BaseModel):
    """Configure extractor settings."""

    max_concurrent: int = Field(default=5, gt=0)
    enable_llm: bool = True
    max_papers: int = Field(default=50, gt=0, le=200)
    per_paper_timeout_ms: int = Field(default=20000, ge=1000, le=120000)


class ObservabilityConfig(BaseModel):
    """Configure observability settings."""

    enabled: bool = True
    langfuse_host: str = "http://localhost:3000"
    payload_mode: Literal["full_redacted", "metadata_only"] = "full_redacted"


class EvidenceRewriteConfig(BaseModel):
    """Configure evidence rewrite settings."""

    max_items: int = Field(default=30, ge=1, le=100)
    max_chars: int = Field(default=15000, ge=1000, le=60000)
    min_body_length_ratio: float = Field(default=0.5, gt=0, le=1.0)
    min_paragraph_ratio: float = Field(default=0.5, gt=0, le=1.0)


class RelevanceConfig(BaseModel):
    """Configure relevance settings."""

    max_papers: int = Field(default=50, gt=0, le=200)
    min_papers: int = Field(default=10, ge=0, le=200)
    cross_encoder_min_score: float | None = None
    lexical_min_score: float = Field(default=0.0, ge=0.0, le=3.0)

    @model_validator(mode="after")
    def _validate_policy(self):
        if self.min_papers > self.max_papers:
            raise ValueError("relevance.min_papers must be <= max_papers")
        if self.cross_encoder_min_score is not None and not math.isfinite(
            self.cross_encoder_min_score
        ):
            raise ValueError("cross_encoder_min_score must be finite or null")
        return self


class EvalConfig(BaseModel):
    """Configure evaluator and evidence-rewrite limits."""

    max_tokens: int = Field(default=16384, gt=0)
    faithfulness_max_evidence_items: int = Field(default=40, ge=1, le=100)
    faithfulness_max_context_chars: int = Field(default=24000, ge=1000, le=80000)
    rewrite: EvidenceRewriteConfig = Field(default_factory=EvidenceRewriteConfig)


class AppConfig(BaseModel):
    """Aggregate all LitAgent configuration sections."""

    agent: AgentConfig
    logging: LoggingConfig
    memory: MemoryConfig = MemoryConfig()
    context: ContextConfig = ContextConfig()
    orchestrator: OrchestratorConfig = OrchestratorConfig()
    llm: LLMConfig = LLMConfig()
    adversarial: AdversarialConfig = AdversarialConfig()
    mcp_servers: dict[str, MCPServerConfig] = {}
    safety: SafetyConfig = SafetyConfig()
    resilience: ResilienceConfig = ResilienceConfig()
    extractor: ExtractorConfig = ExtractorConfig()
    relevance: RelevanceConfig = RelevanceConfig()
    observability: ObservabilityConfig = ObservabilityConfig()
    eval: EvalConfig = EvalConfig()
    planner: PlannerConfig = PlannerConfig()

    @model_validator(mode="after")
    def _validate_cross_component_limits(self):
        if self.relevance.max_papers > self.extractor.max_papers:
            raise ValueError("relevance.max_papers must be <= extractor.max_papers")
        return self


def _find_project_root() -> Path:
    current = Path(__file__).resolve().parent
    for parent in current.parents:
        if (parent / "pyproject.toml").exists():
            return parent
    raise FileNotFoundError("Cannot find project root (no pyproject.toml found)")


def _find_config_file(config_path: str | None = None) -> Path:
    """Resolve the explicit, environment, or default configuration path."""
    if config_path:
        path = Path(config_path)
    elif os.environ.get("LITAGENT_CONFIG"):
        path = Path(os.environ["LITAGENT_CONFIG"])
    else:
        path = _find_project_root() / "config" / "default.yaml"

    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    return path


def _apply_env_overrides(data: dict, prefix: str = "LITAGENT_") -> dict:
    """Apply declared environment overrides while preserving value types."""
    for env_key, env_val in os.environ.items():
        if not env_key.startswith(prefix):
            continue

        rest = env_key[len(prefix) :].lower()

        parts = rest.split("_", 1)
        if len(parts) != 2:
            continue

        section, key = parts

        # Ignore unknown names so typos cannot create undeclared settings.
        if section in data and isinstance(data[section], dict) and key in data[section]:
            original = data[section][key]

            # bool must be checked before int because bool subclasses int.
            if isinstance(original, bool):
                data[section][key] = env_val.strip().lower() in (
                    "1",
                    "true",
                    "yes",
                    "on",
                )
            elif isinstance(original, int):
                data[section][key] = int(env_val)
            elif isinstance(original, float):
                data[section][key] = float(env_val)
            else:
                data[section][key] = env_val

    return data


def load_config(config_path: str | None = None) -> AppConfig:
    """Load, override, and validate the application configuration."""

    config_file = _find_config_file(config_path)

    with open(config_file, "r", encoding="utf-8") as f:
        raw = yaml.safe_load(f)

    raw = _apply_env_overrides(raw)

    try:
        return AppConfig(**raw)
    except ValidationError as e:
        from litagent.exceptions import ConfigError

        raise ConfigError(f"Invalid config: {e}") from e
